sudo: required
dist: bionic

services:
        - docker

env:
        - CTR_ENGINE=docker

before_install:
        - sudo apt-get install -qq bats shellcheck

script:
        - make validate
        - make build-container
        - make test-integration
